[package]
name = "basic_web_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.11"
rusqlite = {version = "0.28.0", features = ["bundled"]}
